//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValCacheProxyLib.FileServerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileServerService.IFileServer")]
    public interface IFileServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServer/GetFile", ReplyAction="http://tempuri.org/IFileServer/GetFileResponse")]
        System.IO.Stream GetFile(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServer/GetFile", ReplyAction="http://tempuri.org/IFileServer/GetFileResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> GetFileAsync(string filename);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServer/GetAvailableFiles", ReplyAction="http://tempuri.org/IFileServer/GetAvailableFilesResponse")]
        string[] GetAvailableFiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileServer/GetAvailableFiles", ReplyAction="http://tempuri.org/IFileServer/GetAvailableFilesResponse")]
        System.Threading.Tasks.Task<string[]> GetAvailableFilesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileServerChannel : ValCacheProxyLib.FileServerService.IFileServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileServerClient : System.ServiceModel.ClientBase<ValCacheProxyLib.FileServerService.IFileServer>, ValCacheProxyLib.FileServerService.IFileServer {
        
        public FileServerClient() {
        }
        
        public FileServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.IO.Stream GetFile(string filename) {
            return base.Channel.GetFile(filename);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> GetFileAsync(string filename) {
            return base.Channel.GetFileAsync(filename);
        }
        
        public string[] GetAvailableFiles() {
            return base.Channel.GetAvailableFiles();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAvailableFilesAsync() {
            return base.Channel.GetAvailableFilesAsync();
        }
    }
}
